# -*- coding: utf-8 -*-
"""dataforpostgresql.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lzm982vr6_mBTPwS2bUwov6nQuGvq2MS
"""



import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("Vader_labled_data.csv")

engine = create_engine('postgresql://postgres:NFvpbWt78@128.226.28.177:5432/data')

df.to_sql('data',engine,index=False, if_exists='replace')